apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-auto-scalling

spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    kind: Deployment
    name: my-scaling-deployment
  targetCPUUtilizationPercentage: 30