apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env-secret

spec:
  containers:
    - name: nginx-container
      image: nginx
      # env with secret
      env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: database_pass
              name: secret-name
