apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-service
  labels:
    component: aws-load-balancer-service

spec:
  type: LoadBalancer # creates an classic aws loadbalancer
  selector:
    component: nginx-pod
  ports:
    - port: 80
